branches:
  only:
  - master
  - demo
  - /^rc-\d+\.\d+/

services:
  - docker

language: cpp
os: linux
dist: bionic

env:
  global:
    - GLOBALVAR=imaglobalvar
    - BUILD_ARTEFACTS_DIR=$TRAVIS_BUILD_DIR/artefacts/$TRAVIS_BUILD_NUMBER
  matrix:
    - BUILD=1 TAG=1TAG
    - BUILD=2 TAG=2TAG

before_install: 
  - echo "before install make directory for build $TRAVIS_BUILD_NUMBER"
  - mkdir -p $BUILD_ARTEFACTS_DIR

install: echo "No install action required"

script:
  - echo "Running build $BUILD $TAG"
  - echo $BUILD $TAG | tee > $BUILD_ARTEFACTS_DIR/build_$BUILD.txt

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: echo TEST $BUILD $TAG | tee > $BUILD_ARTEFACTS_DIR/test.txt

    - stage: deploy
      env:
      install:
      before_script: 
        - mkdir -p $TRAVIS_BUILD_NUMBER
        - echo "HELLOOOO this is travis build $TRAVIS_BUILD_NUMBER" | tee > $BUILD_ARTEFACTS_DIR/deploy.txt
      script:
        - cat $BUILD_ARTEFACTS_DIR/*
      # the deploy stage is used for tagging the build on GitHub
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name "builds@travis-ci.com"
        - git config --local user.email "Travis CI"
        - export FIRMWARE_VERSION=$(./version.sh)
        - export TRAVIS_TAG=v$FIRMWARE_VERSION
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        body: Release automatically generated from TravisCI build $TRAVIS_BUILD_NUMBER.
        prerelease: true
        file: $BUILD_ARTEFACTS_DIR/deploy.txt
        on:
          branch: master

#https://github.com/travis-ci/travis-ci/issues/1476