language: cpp
os: linux
dist: trusty

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
    - ARTIFACTS_BUCKET=beetest
    - S3_STORAGE_LOCATION=s3://$ARTIFACTS_BUCKET/test/build/$TRAVIS_BUILD_NUMBER
  matrix:
    - BUILD=1 TAG=k
    - BUILD=2 TAG=2TAG

before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync $S3_STORAGE_LOCATION ~/$TRAVIS_BUILD_NUMBER

install: echo $TAG

script: echo $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/build_$BUILD.txt

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: echo TEST $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/test.txt
    #- name: "Build"
    #  env: BUILD=1 TAG=k
      
    #- name: "Build 2"
    #  env: BUILD=2 TAG=J
    #  script: echo $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/build_$BUILD.txt

    - stage: deploy
      env: BLA=cu
      script:
        - cat ~/$TRAVIS_BUILD_NUMBER/*
      after_success:
        #- aws s3 rm --recursive $S3_STORAGE_LOCATION  # clean up after ourselves

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER $S3_STORAGE_LOCATION 