language: cpp
os: linux
dist: trusty

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
    - ARTIFACTS_BUCKET=beetest
    - S3_STORAGE_LOCATION=s3://$ARTIFACTS_BUCKET/test/build/$TRAVIS_BUILD_NUMBER

before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync $S3_STORAGE_LOCATION ~/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: "Tests and Builds"
      name: "Unit Tests"
      script: echo TEST | tee > ~/$TRAVIS_BUILD_NUMBER/test.txt
    - name: "Build 1"
      env: BUILD=1 TAG=k
      script: echo $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/build_$BUILD.txt
    - name: "Build 2"
      env: BUILD=2 TAG=J
      script: echo $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/build_$BUILD.txt

    - stage: "Deploy"
      script:
        - cat ~/$TRAVIS_BUILD_NUMBER/*
      after_success:
        #- aws s3 rm --recursive $S3_STORAGE_LOCATION  # clean up after ourselves

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER $S3_STORAGE_LOCATION 