branches:
  only:
  - master
  - demo
  - /^rc-\d+\.\d+/

services:
  - docker

language: cpp
os: linux
dist: bionic

env:
  global:
    - GLOBALVAR=imaglobalvar
  matrix:
    - BUILD=1 TAG=k
    - BUILD=2 TAG=2TAG
    - BUILD=3 TAG=asdflj

before_install: 
  - echo "before install"
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER

install: echo "No install action required"

script:
  - echo "Running build $BUILD $TAG"
  - echo $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/build_$BUILD.txt

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: echo TEST $BUILD $TAG | tee > ~/$TRAVIS_BUILD_NUMBER/test.txt

    - stage: deploy
      env:
      install:
      before_script: 
        - mkdir -p ~/$TRAVIS_BUILD_NUMBER
        - echo "HELLOOOO" | tee > ~/$TRAVIS_BUILD_NUMBER/deploy.txt
      script:
        - cat ~/$TRAVIS_BUILD_NUMBER/*

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "markuckermann"
      - git config --local user.email "mark.uckermann@gmail.com"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      on:
        branch: master

#https://github.com/travis-ci/travis-ci/issues/1476